Fix perf tools compile error on Linux5.4
when compiling perf tools in Linux 5.4, it will
encounter compile error like this:

bench/futex.h:37:10: error: 'SYS_futex' undeclared
(first use in this function); did you mean 'SYS_tee'?
syscall(SYS_futex, uaddr, op | opflags, val, timeout, uaddr2, val3)
          ^
Add require definition to cope with 32 to 64 bit time_t compatibility,
including fstat clone3 and other affected syscalls.

Signed-off-by: Eric Lin <tesheng@andestech.com>